resources:
- ../../base

# OSV Operator
patches:
- target:
    kind: Subscription
    name: hco-operatorhub
  patch: |
    - op: replace
      path: /spec/channel
      value: stable

- target:
    kind: Namespace
  patch: |
    - op: add
      path: /metadata/labels/ci_environment
      value: nonprod

# Node Health Check Operator
- target:
    kind: Subscription
    name: node-health-check-operator
  patch: |
    - op: replace
      path: /spec/channel
      value: stable
