resources:
- ../../base

# Openshift Virtualization Operator
patches:
- target:
    kind: Subscription
    name: hco-operatorhub
  patch: |
    - op: replace
      path: /spec/channel
      value: stable

- target:
    kind: Namespace
  patch: |
    - op: add
      path: /metadata/labels/ci_environment
      value: prod

# Node Health Check Operator
- target:
    kind: Subscription
    name: node-health-check-operator
  patch: |
    - op: replace
      path: /spec/channel
      value: stable

# Kube Descheduler Operator
- target:
    kind: Subscription
    name: cluster-kube-descheduler-operator
  patch: |
    - op: replace
      path: /spec/channel
      value: stable