apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: osv-lab-placement
  namespace: acm-config
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: ocp_osv_override
              operator: DoesNotExist
            - key: environment
              operator: In
              values:
                - lab
            - key: ocp_osv
              operator: Exists