apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# OpenShift Virtualization Operator
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
# Node Health Check Operator
- namespace-nho.yaml
- operatorgroup-nho.yaml
- subscription-nho.yaml
# Fence Agents Remediation Operator
- namespace-far.yaml
- operatorgroup-far.yaml
- subscription-far.yaml
# Kube Descheduler Operator
- namespace-ds.yaml
- operatorgroup-ds.yaml
- subscription-ds.yaml

